name: github pages

# Only run this when the master branch changes
on: push

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: j0-0sko
          dockerfile: .devcontainer/Dockerfile
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: prog1
      
  deploy-book:
    needs: build_docker_image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: ghcr.io/j0-0sko/prog1:latest
    steps:
    - uses: actions/checkout@v2

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build zapiski

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./zapiski/_build/html
