name: github pages

# Only run this when the master branch changes
on: push

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/jo-osko/prog1:latest
      
  deploy-book:
    needs: build_docker_image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: ghcr.io/j0-0sko/prog1:latest
    steps:
    - uses: actions/checkout@v2

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build zapiski

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./zapiski/_build/html