name: github pages

# Only run this when the master branch changes
on: push

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:


  deploy-book:
    # needs: build_docker_image
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # container: ghcr.io/j0-0sko/prog1:latest
    container: j00sko/programiranje1:latest
    steps:
    - name: Before
      run: |
        jupyter kernelspec list
    - 
      uses: actions/checkout@v2
      with: 
        path: "prog1"
    # Build the book
    - name: Build the book
      run: |
        opam init --disable-sandboxing
        ocaml-jupyter-opam-genspec
        jupyter kernelspec install --name ocaml-jupyter "$(opam var share)/jupyter" --user
        jupyter kernelspec list
        jupyter-book build prog1/zapiski

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./prog1/zapiski/_build/html
